export const contactDataTypeOptions = [
  { value: 0, label: 'None' },
  { value: 1, label: 'Glucose' },
  { value: 2, label: 'HbA1c' },
  { value: 3, label: 'Insulin' },
  { value: 4, label: 'UREA NITROGEN ' },
  { value: 5, label: 'Creatinine' },
  { value: 6, label: 'eGFR NON-AFR. AMERICAN' },
  { value: 7, label: 'eGFR AFRICAN AMERICAN' },
  { value: 8, label: 'URIC ACID' },
  { value: 9, label: 'PROTEIN TOTAL' },
  { value: 10, label: 'ALBUMIN' },
  { value: 11, label: 'BILIRUBIN, TOTAL' },
  { value: 12, label: 'BILIRUBIN, INDIRECT ' },
  { value: 13, label: 'BILIRUBIN, DIRECT' },
  { value: 14, label: 'ALKALINE PHOSPHATASE' },
  { value: 15, label: 'AST (SGOT)' },
  { value: 16, label: 'ALT (SGPT)' },
  { value: 17, label: 'AST/ALT (formula)' },
  { value: 18, label: 'AST/ALT (formula)' },
  { value: 19, label: 'GGT (Gamma Glutamyl Transpeptidase)' },
  { value: 20, label: 'TSH' },
  { value: 21, label: 'T3, FREE' },
  { value: 22, label: 'T4, FREE' },
  { value: 23, label: '(FreeT3)/(FreeT4)' },
  { value: 24, label: 'Thyroid Antibodies' },
  { value: 25, label: 'Thyroid Antibodies' },
  { value: 26, label: 'PTH intact (Parathyroid Hormone)' },
  { value: 27, label: 'TESTOSTERONE, TOTAL, MS' },
  { value: 28, label: 'TESTOSTERONE, FREE' },
  { value: 29, label: 'TESTOSTERONE,BIOAVAILABLE' },
  { value: 30, label: 'SEX HORMONE BINDING GLOBULIN' },
  { value: 31, label: 'PROLACTIN' },
  { value: 32, label: 'FSH' },
  { value: 33, label: 'LH' },
  { value: 34, label: 'LH/FSH' },
  { value: 35, label: 'TRIGLYCERIDES' },
  { value: 36, label: 'CHOLESTEROL, TOTAL' },
  { value: 37, label: 'HDL-CHOLESTEROL' },
  { value: 38, label: 'CHOLESTEROL,TOTAL/HDL ' },
  { value: 39, label: 'LDL-CHOLESTEROL' },
  { value: 40, label: 'CATR ' },
  { value: 41, label: 'VLDL ' },
  { value: 42, label: 'FERRITIN' },
  { value: 43, label: 'IRON, TOTAL' },
  { value: 44, label: 'IRON BINDING CAPACITY' },
  { value: 45, label: '% SATURATION' },
  { value: 46, label: 'TRANSFERRIN' },
  { value: 47, label: 'HOMOCYSTEINE' },
  { value: 48, label: 'C-PEPTIDE' },
  { value: 49, label: 'C-REACTIVE PROTEIN' },
  { value: 50, label: 'CREATINE KINASE, TOTAL' },
  { value: 51, label: 'Eosinophil cationic protein (ECP)' },
  { value: 52, label: 'VITAMIN D,25-OH,TOTAL,IA' },
  { value: 53, label: 'VITAMIN B12' },
  { value: 54, label: 'FOLATE, SERUM' },
  { value: 55, label: 'LDH (lactic dehydrogenase)' },
  { value: 56, label: 'IL-6' },
  { value: 57, label: 'Creatinphosphokinase (CPK)' },
  { value: 58, label: 'CPK-MB' },
  { value: 59, label: 'Cortisol (better in saliva)' },
  { value: 60, label: 'DHEA-S' },
  { value: 61, label: 'Caeruloplasmin' },
  { value: 62, label: 'Fibrinogen' },
  { value: 63, label: 'Somatometdin C' },
  { value: 64, label: 'TIBS' },
  { value: 65, label: 'Somatometdin C' },
  { value: 66, label: 'Ionized calcium' },
  { value: 67, label: 'Potassum' },
  { value: 68, label: 'Calcium' },
  { value: 69, label: 'Phosphorus' },
  { value: 70, label: 'Sodium' },
  { value: 71, label: 'Chloride' },
  { value: 72, label: 'Iodine' },
  { value: 73, label: 'Magnesium' },
  { value: 74, label: 'Cu' },
  { value: 75, label: 'Zn' },
  { value: 76, label: 'Cu/Zn' },
  { value: 77, label: 'HBC' },
  { value: 78, label: 'RBC' },
  { value: 79, label: 'MCV' },
  { value: 80, label: 'MCH' },
  { value: 81, label: 'MCHC' },
  { value: 82, label: 'RDW' },
  { value: 83, label: 'HCT' },
  { value: 84, label: 'PLT' },
  { value: 85, label: 'MPV' },
  { value: 86, label: 'WBC' },
  { value: 87, label: 'NEUT #%' },
  { value: 88, label: 'EO #%' },
  { value: 89, label: 'BAS #%' },
  { value: 90, label: 'LYM #%' },
  { value: 91, label: 'MON #%' },
  { value: 92, label: 'ESR' },
  { value: 93, label: 'PCT' },
  { value: 94, label: 'PDW' },
];

export const allCauses = [
  { value: 0, label: 'None' },
  { value: 1, label: 'unbalanced diet' },
  { value: 2, label: 'fats insufficiency' },
  { value: 3, label: 'fats deficit' },
  { value: 4, label: 'glucose intolerance' },
  { value: 5, label: 'Type-1 diabete' },
  { value: 6, label: 'Type-2 diabete' },
  { value: 7, label: 'No disease' },
  { value: 8, label: 'Diabete' },
  { value: 9, label: 'iron deficiency' },
  { value: 10, label: 'Stress' },
  { value: 11, label: 'anemia' },
  { value: 12, label: 'chronic inflammation' },
  { value: 13, label: 'low light level inflamation' },
  { value: 14, label: 'stress shock' },
];

export const allRecommendations = [
  { value: 1, label: 'recommendation 1' },
  { value: 2, label: 'recommendation 2' },
];

export const PATH_TYPES = [
  { value: 'low', label: 'low' },
  { value: 'below_reference', label: 'below_reference' },
  { value: 'ideal', label: 'ideal' },
  { value: 'above_reference', label: 'above_reference' },
  { value: 'high', label: 'high' },
];

export const allQuestions = [
  { value: 0, label: 'None' },
  { value: 1, label: 'Little interest or pleasure in doing things' },
  { value: 2, label: 'Feeling down, depressed, or hopeless' },
  {
    value: 3,
    label: 'Trouble falling or staying asleep, or sleeping too much',
  },
  { value: 4, label: 'Feeling tired or having little energy' },
  { value: 5, label: 'Poor appetite or overeating' },
  {
    value: 6,
    label:
      'Feeling bad about yourself or that you are a failure or have let yourself or your family down',
  },
  {
    value: 7,
    label:
      'Trouble concentrating on things, such as reading the newspaper or watching television',
  },
  {
    value: 8,
    label:
      'Moving or speaking so slowly that other people could have noticed. Or the opposite being so fidgety or restless that you have been moving around a lot more than usual',
  },
];

export const PATH_QUESTION = [
  { value: 'not_at_all', label: 'not_at_all' },
  { value: 'several_days', label: 'several_days' },
  { value: 'more_than_half_the_days', label: 'more_than_half_the_days' },
  { value: 'nearly_every_day', label: 'nearly_every_day' },
];
